[package]
name = "alltalk-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
rodio = "0.19.0"
serde = { version = "1.0.210", features = ["derive"] }
stream-download = "0.9.0"
