[package]
name = "alltalk-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "^0.12.2", features = ["json"] }
rodio = "^0.19"
serde = { version = "^1.0.113", features = ["derive"] }
stream-download = "^0.9"
thiserror = "^1.0.49"
